on:
  push:
    branches: [ "dev" ]
    paths:
    - 'src/**'
    - pom.xml
    - '.github/workflows/publish-to-repo.yaml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: action

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: maven-settings-xml-action
      uses: whelk-io/maven-settings-xml-action@v22
      with:
        repositories: '[{"id": "maven-snapshots", "url": "https://repo.knighthat.me/repository/maven-snapshots/"}]'
        servers: ' [{"id": "publisher", "username": "${{ secrets.REPO_NAME }}", "password": "${{ secrets.REPO_PASSWD }}"}]'
        output_file: ".m2/settings.xml"

    - name: Deploy to remote repository
      run: mvn deploy --settings .m2/settings.xml -Dmaven.test.skip=true